name: Deploy pagina web

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Preparar pagina
        run: |
          mkdir _site
          cp -r pagina_web/* _site/

      - name: Subir pagina
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Publicar
        id: deployment
        uses: actions/deploy-pages@v4